dist: bionic
language: python
cache: pip
python: "3.7"
before_install:
  - pip install poetry
install:
  - poetry install -v
env:
  - TAMU_API_KEY=00000000000000000000000000000000
script:
  - make test
  - make lint
branches:
  only:
    - master
notifications:
  email: false
