version: '2'

volumes:
  geodude-data:
    driver: local

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TAMU_API_KEY
    volumes:
      - geodude-data:/data/geodude:rw
